[phases.install]
cmds = [
  "cd app && npm ci"
]

[phases.build]
cmds = [
  "cd cubeway && wasm-pack build --target web",
  "cd app && npm run build"
]

[pkgs]
packages = ["wasm-pack", "nodejs_22"]

[tools]
rust = { version = "stable" }
