[package]
name = "cubeway"
version = "0.1.0"
edition = "2021"
description = "A sample project with wasm-pack"
repository = "https://github.com/stevenhuyn/hello-wasm"

[lib]
name = "cubeway"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cubeway-native"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2"
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.16"
cfg-if = "1"
pollster = "0.3"


[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "0.16", features = ["webgl"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}


[profile.release]
lto = true
opt-level = 's'


 

 